export interface CongressTrade {
  id: string;
  politician: string;
  party: "D" | "R";
  chamber: "Senate" | "House";
  state: string;
  ticker: string;
  companyName: string;
  type: "Buy" | "Sell";
  amount: string;
  transactionDate: string;
  filedDate: string;
  daysAgo: number;
  committee?: string;
}

export const MOCK_CONGRESS_TRADES: CongressTrade[] = [
  {
    id: "ct-001",
    politician: "Tommy Tuberville",
    party: "R",
    chamber: "Senate",
    state: "AL",
    ticker: "NVDA",
    companyName: "NVIDIA",
    type: "Buy",
    amount: "$100,001 - $250,000",
    transactionDate: "2026-07-28",
    filedDate: "2026-08-04",
    daysAgo: 2,
    committee: "Armed Services",
  },
  {
    id: "ct-002",
    politician: "Nancy Pelosi",
    party: "D",
    chamber: "House",
    state: "CA",
    ticker: "CRWD",
    companyName: "CrowdStrike",
    type: "Buy",
    amount: "$500,001 - $1,000,000",
    transactionDate: "2026-07-25",
    filedDate: "2026-08-03",
    daysAgo: 3,
    committee: "Intelligence",
  },
  {
    id: "ct-003",
    politician: "Dan Crenshaw",
    party: "R",
    chamber: "House",
    state: "TX",
    ticker: "PANW",
    companyName: "Palo Alto Networks",
    type: "Buy",
    amount: "$15,001 - $50,000",
    transactionDate: "2026-07-22",
    filedDate: "2026-08-01",
    daysAgo: 5,
    committee: "Intelligence",
  },
  {
    id: "ct-004",
    politician: "Mark Warner",
    party: "D",
    chamber: "Senate",
    state: "VA",
    ticker: "MSFT",
    companyName: "Microsoft",
    type: "Buy",
    amount: "$250,001 - $500,000",
    transactionDate: "2026-07-20",
    filedDate: "2026-07-30",
    daysAgo: 7,
    committee: "Intelligence",
  },
  {
    id: "ct-005",
    politician: "Josh Gottheimer",
    party: "D",
    chamber: "House",
    state: "NJ",
    ticker: "GOOGL",
    companyName: "Alphabet",
    type: "Buy",
    amount: "$50,001 - $100,000",
    transactionDate: "2026-07-18",
    filedDate: "2026-07-28",
    daysAgo: 9,
  },
  {
    id: "ct-006",
    politician: "Markwayne Mullin",
    party: "R",
    chamber: "Senate",
    state: "OK",
    ticker: "AVGO",
    companyName: "Broadcom",
    type: "Buy",
    amount: "$100,001 - $250,000",
    transactionDate: "2026-07-15",
    filedDate: "2026-07-25",
    daysAgo: 12,
  },
  {
    id: "ct-007",
    politician: "Michael McCaul",
    party: "R",
    chamber: "House",
    state: "TX",
    ticker: "TSM",
    companyName: "TSMC",
    type: "Buy",
    amount: "$50,001 - $100,000",
    transactionDate: "2026-07-14",
    filedDate: "2026-07-24",
    daysAgo: 13,
    committee: "Foreign Affairs",
  },
  {
    id: "ct-008",
    politician: "Ro Khanna",
    party: "D",
    chamber: "House",
    state: "CA",
    ticker: "AMD",
    companyName: "AMD",
    type: "Buy",
    amount: "$15,001 - $50,000",
    transactionDate: "2026-07-12",
    filedDate: "2026-07-22",
    daysAgo: 15,
    committee: "Armed Services",
  },
  {
    id: "ct-009",
    politician: "Pete Ricketts",
    party: "R",
    chamber: "Senate",
    state: "NE",
    ticker: "NET",
    companyName: "Cloudflare",
    type: "Buy",
    amount: "$15,001 - $50,000",
    transactionDate: "2026-07-10",
    filedDate: "2026-07-20",
    daysAgo: 17,
  },
  {
    id: "ct-010",
    politician: "Nancy Pelosi",
    party: "D",
    chamber: "House",
    state: "CA",
    ticker: "NVDA",
    companyName: "NVIDIA",
    type: "Buy",
    amount: "$1,000,001 - $5,000,000",
    transactionDate: "2026-07-08",
    filedDate: "2026-07-18",
    daysAgo: 19,
  },
  {
    id: "ct-011",
    politician: "Tommy Tuberville",
    party: "R",
    chamber: "Senate",
    state: "AL",
    ticker: "ASML",
    companyName: "ASML",
    type: "Buy",
    amount: "$50,001 - $100,000",
    transactionDate: "2026-07-05",
    filedDate: "2026-07-15",
    daysAgo: 22,
    committee: "Armed Services",
  },
  {
    id: "ct-012",
    politician: "Shelley Moore Capito",
    party: "R",
    chamber: "Senate",
    state: "WV",
    ticker: "CEG",
    companyName: "Constellation Energy",
    type: "Buy",
    amount: "$100,001 - $250,000",
    transactionDate: "2026-07-03",
    filedDate: "2026-07-13",
    daysAgo: 24,
    committee: "Environment & Public Works",
  },
];

export function getTradesForTicker(ticker: string): CongressTrade[] {
  return MOCK_CONGRESS_TRADES.filter((t) => t.ticker === ticker);
}

export function getRecentTrades(limit = 10): CongressTrade[] {
  return MOCK_CONGRESS_TRADES.slice(0, limit);
}
