/**
 * Everything about the demonstration source except its values.
 *
 * Split out from `demonstration.ts` so that the access gate can be evaluated
 * without pulling the fixture into the module graph. That is not tidiness: the
 * fixture is a few hundred kilobytes, and a page that imports it in order to
 * decide *not* to show it would ship the whole thing to every production
 * visitor and then decline to render a single value from it.
 *
 * So the rule for this file is that it must never import the JSON, and nothing
 * it exports may require reading a value.
 */

import { selfGeneratedRights, type DataRights } from "../rights.ts";
import type { SourceProvenance } from "../types.ts";

export const DEMONSTRATION_PROVIDER_ID = "outfox-demonstration-v1";
export const DEMONSTRATION_PROVIDER_NAME = "Outfox demonstration series";

export const DEMONSTRATION_LABEL = "Demonstration data — not actual market performance.";

/** Kept in step with the generator by `tests/fund-fixtures.test.ts`. */
export const DEMONSTRATION_GENERATED_AT = "2026-09-05T00:00:00.000Z";

/**
 * Rights on data we generated ourselves.
 *
 * Everything is granted because there is no counterparty — it came from a seed
 * and an equation. A right to display is not a right to mislead, so the
 * provenance below also carries the label that must appear wherever the values
 * do, and `kind: "demonstration"` makes that machine-checkable.
 */
export const DEMONSTRATION_RIGHTS: DataRights = selfGeneratedRights(
  "Generated by Outfox from a fixed seed with no third-party input. No licence " +
    "is required because no third party's data is involved.",
  DEMONSTRATION_GENERATED_AT
);

export function demonstrationProvenance(method: string): SourceProvenance {
  return {
    sourceId: DEMONSTRATION_PROVIDER_ID,
    sourceName: DEMONSTRATION_PROVIDER_NAME,
    kind: "demonstration",
    rights: DEMONSTRATION_RIGHTS,
    producedAt: DEMONSTRATION_GENERATED_AT,
    method,
    demonstrationLabel: DEMONSTRATION_LABEL,
  };
}
