/**
 * Domain types for fund comparison.
 *
 * Written so that connecting a licensed data provider later is a matter of
 * implementing `FundDataProvider`, not rewriting the interface. Nothing here
 * names a vendor, and no component may.
 *
 * Four rules run through the whole file.
 *
 * **Unavailable is not zero.** Every value a source may not supply is an
 * `Availability<T>` carrying a reason, so a missing expense ratio can never be
 * rendered as 0.00% and a missing weight can never be counted as absent
 * exposure.
 *
 * **Price return is not total return.** They are separate bases carried on
 * every series, and a caller asking for one never silently receives the other.
 * A price series says what a share price did; it is not what an investor got,
 * and the type system is where that distinction is enforced rather than in a
 * footnote.
 *
 * **Partial holdings stay partial.** A snapshot covering 62% of a portfolio
 * describes 62% of a portfolio. Known, unmapped and unavailable weight are kept
 * as separate quantities summing to 100 — normalising the known slice up to 100
 * would turn "we can see two thirds of this fund" into "this is the whole
 * fund", which is the single most misleading thing this model could do.
 *
 * **Rights are not a boolean.** See `./rights.ts`. Every dataset carries the
 * set of things it is actually permitted to be used for, and everything fails
 * closed when that set is empty or unexamined.
 */

import type { DataRights } from "./rights.ts";
import type { FundLegalIdentity } from "./identity.ts";

// --- availability ------------------------------------------------------------

export type UnavailableReason =
  | "source_not_connected"
  | "basis_not_supplied"
  | "not_published_by_issuer"
  | "outside_snapshot_coverage"
  | "no_common_date"
  | "rights_not_established"
  | "licensing_restricted"
  | "stale_beyond_threshold"
  | "parse_failed";

export type Available<T> = { status: "available"; value: T; asOf: string; sourceId: string };
export type Unavailable = { status: "unavailable"; reason: UnavailableReason; detail?: string };
export type Availability<T> = Available<T> | Unavailable;

export const unavailable = <T,>(reason: UnavailableReason, detail?: string): Availability<T> => ({
  status: "unavailable",
  reason,
  detail,
});

export const available = <T,>(value: T, asOf: string, sourceId: string): Availability<T> => ({
  status: "available",
  value,
  asOf,
  sourceId,
});

export function isAvailable<T>(value: Availability<T>): value is Available<T> {
  return value.status === "available";
}

/** Human text for an absence. Never returns an empty string, and never a number. */
export function describeUnavailable(reason: UnavailableReason): string {
  switch (reason) {
    case "source_not_connected": return "Unavailable — data source not connected yet";
    case "basis_not_supplied": return "Unavailable — this source does not supply that return basis";
    case "not_published_by_issuer": return "Unavailable — not published by the issuer";
    case "outside_snapshot_coverage": return "Unavailable — outside the coverage of this dataset";
    case "no_common_date": return "Unavailable — the selected funds share no common date";
    case "rights_not_established": return "Unavailable — rights for this source have not been established";
    case "licensing_restricted": return "Unavailable — rights do not permit displaying this";
    case "stale_beyond_threshold": return "Unavailable — the latest data is too old to show";
    case "parse_failed": return "Unavailable — the source value could not be read";
  }
}

// --- provenance --------------------------------------------------------------

/**
 * Where a dataset came from and what may be done with it.
 *
 * `kind` is the load-bearing field. `demonstration` data is generated by Outfox
 * and describes nothing real; `licensed` data comes from a provider under terms.
 * Anything that renders a value must be able to tell the two apart, which is why
 * this is a required discriminator and not an optional note.
 */
export interface SourceProvenance {
  sourceId: string;
  sourceName: string;
  kind: "demonstration" | "licensed";
  rights: DataRights;
  /** When the data was produced or captured. */
  producedAt: string;
  /** How it was produced, so a reader can audit the path. */
  method: string;
  /**
   * Required on demonstration sources: the exact words shown wherever its
   * values appear. Absent on licensed sources, which describe real markets.
   */
  demonstrationLabel?: string;
}

/** True when values from this source must be labelled as demonstration output. */
export function requiresDemonstrationLabel(provenance: SourceProvenance): boolean {
  return provenance.kind === "demonstration";
}

/** How completely a dataset covers what it claims to describe. */
export interface Coverage {
  firstDate: string | null;
  lastDate: string | null;
  observations: number;
  /** Dates the source does not cover, e.g. a halt or a reporting gap. */
  gaps: Array<{ from: string; to: string; reason: string }>;
}

// --- return basis ------------------------------------------------------------

/**
 * What a return series accounts for.
 *
 * `price_return` is the change in share price and nothing else.
 * `total_return` reflects splits *and* distributions, reinvested — the basis
 * Outfox's eventual primary comparison should use, because it is the one that
 * answers what an investor actually got.
 *
 * They are distinct types on purpose. Labelling a price series as total return
 * overstates every income-paying fund and understates nothing, which biases a
 * comparison consistently in one direction.
 */
export type ReturnBasis = "price_return" | "total_return";

export function describeBasis(basis: ReturnBasis): string {
  return basis === "total_return"
    ? "Total return — includes distributions, reinvested, and is adjusted for splits."
    : "Price return — the change in share price only. Distributions are not included.";
}

/** Short label safe to place next to a figure. Never says "growth" or "return you earned". */
export function basisLabel(basis: ReturnBasis): string {
  return basis === "total_return" ? "Total return" : "Price change";
}

export interface ReturnMethodology {
  basis: ReturnBasis;
  /** True when prior values are restated across share splits. */
  splitAdjusted: boolean;
  /** True when distributions are reflected. Must be true for `total_return`. */
  distributionAdjusted: boolean;
  /** What the basis leaves out, for display next to any figure derived from it. */
  excludes: string[];
  /** How the adjustment claims were established, so they are checkable. */
  adjustmentEvidence: string;
}

/**
 * A methodology that claims `total_return` without distributions is incoherent.
 *
 * Enforced rather than documented, because the failure is invisible: the numbers
 * still compute, they are just the wrong numbers under the right label.
 */
export function methodologyIsCoherent(methodology: ReturnMethodology): boolean {
  if (methodology.basis === "total_return") return methodology.distributionAdjusted;
  return !methodology.distributionAdjusted;
}

// --- fund identity -----------------------------------------------------------

/**
 * What the interface needs to name a fund.
 *
 * Wraps the EDGAR-sourced legal identity rather than restating it, so the
 * display name and the registered name cannot drift apart.
 */
export interface FundIdentity {
  symbol: string;
  legal: FundLegalIdentity;
  /** What the interface calls it. Derived from the official name, never invented. */
  displayName: string;
}

export function toFundIdentity(legal: FundLegalIdentity): FundIdentity {
  return { symbol: legal.symbol, legal, displayName: legal.seriesName };
}

// --- price history -----------------------------------------------------------

/**
 * A dated value series.
 *
 * `dates` and `values` are parallel and in ascending date order, and every
 * consumer must look values up **by date**, never by position. Two funds'
 * arrays are not row-aligned: one may be missing a day the other has, and
 * pairing them by index slides every later observation onto the wrong day.
 * `alignment.ts` exists so nothing has to do this by hand.
 */
export interface PriceSeries {
  symbol: string;
  dates: string[];
  values: number[];
  methodology: ReturnMethodology;
  provenance: SourceProvenance;
  coverage: Coverage;
}

/** Value on an exact date, or null when the series has no observation that day. */
export function valueOn(series: PriceSeries, date: string): number | null {
  const index = series.dates.indexOf(date);
  return index === -1 ? null : series.values[index];
}

// --- expenses ----------------------------------------------------------------

export interface ExpenseData {
  symbol: string;
  /** Annual expense ratio as a percentage, e.g. 0.03 for three basis points. */
  expenseRatioPercent: Availability<number>;
  provenance?: SourceProvenance;
}

// --- holdings ----------------------------------------------------------------

export interface Holding {
  /** Ticker when the position is a listed equity we could map. */
  symbol: string | null;
  name: string;
  /** Percentage of the fund's portfolio. Never rescaled. */
  weightPercent: number;
}

/**
 * A holdings snapshot as at one date.
 *
 * The three weight buckets are the point of this type. They are recorded
 * separately and always sum to 100:
 *
 *   knownWeightPercent        positions we have, with weights
 *   unmappedWeightPercent     positions the source gave but we could not map
 *   unavailableWeightPercent  portfolio the source did not disclose to us
 *
 * A caller computing concentration or overlap must decide explicitly what to do
 * with the last two rather than having them silently folded into the first.
 */
export interface HoldingsSnapshot {
  symbol: string;
  asOf: string;
  holdings: Holding[];
  knownWeightPercent: number;
  unmappedWeightPercent: number;
  unavailableWeightPercent: number;
  /** True only when the source supplied the entire portfolio. */
  complete: boolean;
  provenance: SourceProvenance;
}

export interface HoldingsHistory {
  symbol: string;
  snapshots: HoldingsSnapshot[];
  latest: Availability<HoldingsSnapshot>;
}

/** Guard against the normalisation this model exists to prevent. */
export function holdingsWeightsAreConsistent(snapshot: HoldingsSnapshot): boolean {
  const total =
    snapshot.knownWeightPercent + snapshot.unmappedWeightPercent + snapshot.unavailableWeightPercent;
  return Math.abs(total - 100) < 0.01;
}

/**
 * Comparing holdings across funds requires a date they all report.
 *
 * Funds publish on different schedules; comparing a fund's June snapshot with
 * another's March snapshot and calling the difference "overlap" measures the
 * calendar, not the portfolios. This returns the latest date every fund has,
 * along with each fund's own snapshot date so both can be displayed.
 */
export interface HoldingsComparisonBasis {
  commonDate: Availability<string>;
  perFund: Array<{ symbol: string; ownSnapshotDate: string | null }>;
}

export function holdingsComparisonBasis(
  histories: HoldingsHistory[]
): HoldingsComparisonBasis {
  const perFund = histories.map((history) => ({
    symbol: history.symbol,
    ownSnapshotDate: isAvailable(history.latest) ? history.latest.value.asOf : null,
  }));

  if (histories.length === 0) {
    return { commonDate: unavailable("source_not_connected", "No holdings supplied."), perFund };
  }

  const dateSets = histories.map((h) => new Set(h.snapshots.map((s) => s.asOf)));
  const shared = [...(dateSets[0] ?? new Set<string>())]
    .filter((date) => dateSets.every((set) => set.has(date)))
    .sort();

  const latest = shared[shared.length - 1];
  if (!latest) {
    return {
      commonDate: unavailable(
        "no_common_date",
        "These funds have no holdings date in common, so their portfolios cannot be compared."
      ),
      perFund,
    };
  }

  return { commonDate: available(latest, latest, "holdings"), perFund };
}

/**
 * Whether holdings from an issuer may be published.
 *
 * Republishing a fund's holdings, and publishing analysis derived from them,
 * are separate permissions and both are required. Fails closed.
 */
export function holdingsMayBePublished(provenance: SourceProvenance): boolean {
  const { grants } = provenance.rights;
  if (grants.length === 0 || grants.includes("unknown")) return false;
  return (
    grants.includes("redistribution-authorized") &&
    grants.includes("derived-analytics-authorized")
  );
}

// --- disclosure overlays -----------------------------------------------------

/**
 * Disclosed activity touching a fund's holdings.
 *
 * Defined now, unpopulated in this stage. The lanes stay separate: House
 * disclosures, Form 4 insider activity and institutional holdings arrive on
 * different clocks and mean different things, and a combined count would imply
 * they are comparable.
 */
export type DisclosureLane = "house" | "insider" | "institutional";

export interface DisclosureOverlay {
  symbol: string;
  lane: DisclosureLane;
  /** Records touching this fund's holdings, by lane. Never summed across lanes. */
  matches: Availability<number>;
  asOfLane: Availability<string>;
  provenance?: SourceProvenance;
}

// --- the assembled view ------------------------------------------------------

export interface FundRecord {
  identity: FundIdentity;
  prices: Availability<PriceSeries>;
  expenses: ExpenseData;
  holdings: Availability<HoldingsHistory>;
  overlays: DisclosureOverlay[];
}
